name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NOTIFICATION_WEBHOOK: ${{ secrets.NOTIFICATION_WEBHOOK }}
  NOTIFICATION_AUTH: ${{ secrets.NOTIFICATION_AUTH }}

jobs:
  build:
    runs-on: ubuntu-latest
    # insatll nodejs and bun
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

      - name: Send Notification Success
        if: success()
        run: |
          curl -H "Authorization: Bearer ${{ env.NOTIFICATION_AUTH }}" -H "Title:${{ github.event.repository.name }} - Build - ${{ github.ref }}" -d "Build Success - ${{ github.ref }}" ${{ env.NOTIFICATION_WEBHOOK }}

      - name: Send Notification Failure
        if: failure()
        run: |
          curl -H "Authorization: Bearer ${{ env.NOTIFICATION_AUTH }}" -H "Title:${{ github.event.repository.name }} - Build - ${{ github.ref }}" -d "Build Failed - ${{ github.ref }}" ${{ env.NOTIFICATION_WEBHOOK }}
